### ISSUE TITLE
A few issues I discovered (and fixed)

### ISSUE THREAD

**Issue by detrius357** [MMquant/bfx-cpp-api#5]
Sorry for the casual tone. I didn't find another way of telling people about the problems and solutions I discovered working with this and I didn't want the information to be lost. My changes are a bit all over the place so I won't be submitting pull request. Also I'm new here.

- Get requests crashing after Post requests
Post requests set a few cUrl options that are not reset afterwards. Therefore get requests after that fail, specifically because headers are set that got deleted. I fixed this by reseting the cUrl options after Post requests and restoring a few additional options I added (see next).

- Problems with Bitfinex certification
I didn't get it to work before getting a crt file for bitfinex and pointing cUrl towards it using "curl_easy_setopt(curl, CURLOPT_CAINFO, "curl-ca-bundle.crt");".

- Missing Timeout
Bitfinex has a habbit of messing up the connection from time to time (I believe due to cloudflare and DDOS protections) so the lack of a timeout option lead to getting whatever app uses this stuck. So I added "curl_easy_setopt(curl, CURLOPT_TIMEOUT, 30L);" to the initialization.

- "Post only" parameter in new order call
This flag is implemented as boolean but the API actually expects "0" or "1".

Alright, I think that's all. Thanks for the amazing work!

**Comment by MMquant** [comment]
- There is opened pull request regarding this issue but it will not be accepted. It's non-elegant solution. Anyway I will leave it opened till it's not resolved. I was thinking about the exact solution which you've mentioned and it would be nice if you'd make pull request.

- According to the [CURLOPT_CAINFO](https://curl.haxx.se/libcurl/c/CURLOPT_CAINFO.html) man page there exists default CURLOPT_CAINFO setting which points to the system CA certs path. So I prefer not to set explicitly CURLOPT_CAINFO but to check if correct CA bundle is indeed located where it should be. Refer to [this] (https://serverfault.com/questions/485597/default-ca-cert-bundle-location) on how to get you system CA path.

- Can be implemented. You can open pull request.

- This can be fixed as well.

If forementioned issues will not be resolved until the end of December I will have a look into that in January. Now I'm out of the time.

**Comment by MMquant** [comment]
POST then GET request crash fixed

**Comment by MMquant** [comment]
curl timeout setting added.

implementation of newOrder() method should be correct. It accepts bool but it converts C++ bool value to "string booleans". Result bool JSON in requests looks like ... ,"is_postonly":true, ...
According to BFX API documentation _is_postonly_ parameter accepts boolean true or false.

Did you have any issues with it?
